name: Build a snapshot

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Generate single-use GPG key
      run: |
        name="Andrvotr single-use key for $GITHUB_REF $GITHUB_SHA $(date +%s)"
        gpg --yes --batch --pinentry-mode loopback --passphrase "" --quick-generate-key "$name" default default never
    - name: Build with Maven
      run: |
        MAVEN_GPG_PUBLIC_KEY="$(gpg --export --armor)" mvn -B verify
    - uses: actions/upload-artifact@v4
      with:
        path: andrvotr-dist/target/*SNAPSHOT.tar.gz*
